In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
os.chdir('E:/35986/PycharmProjects/PythonProject/Pandas')#设置工作目录

# 交叉表和同学和透视表

In [2]:
#交叉表
df = pd.DataFrame({'性别': ['男', '女', '男', '女', '男', '女'],
                     '是否吸烟': ['是', '否', '是', '否', '是', '否']})
crosstab = pd.crosstab(df['性别'], df['是否吸烟'])#交叉表
print(crosstab)

是否吸烟  否  是
性别
女     3  0
男     0  3

In [5]:
df1 = pd.read_csv('uniqlo.csv')
#根据city和channel列创建交叉表计算销售总额
print(df1.groupby(['city', 'channel']).agg({'revenue': 'sum'}))
print('-----------------------------')
print(df1.groupby(['city', 'channel'], as_index=False).agg({'revenue': 'sum'}))

                revenue
city channel
上海   线上       114438.09
     线下       275383.64
北京   线下       130458.62
南京   线下       123150.93
广州   线上       200893.30
     线下       117231.19
成都   线下       208189.86
杭州   线下       589518.49
武汉   线上       281420.73
     线下       308357.05
深圳   线下       733123.68
西安   线上        30088.01
     线下       180686.61
重庆   线上        26330.35
     线下       237162.30
-----------------------------
   city channel    revenue
0    上海      线上  114438.09
1    上海      线下  275383.64
2    北京      线下  130458.62
3    南京      线下  123150.93
4    广州      线上  200893.30
5    广州      线下  117231.19
6    成都      线下  208189.86
7    杭州      线下  589518.49
8    武汉      线上  281420.73
9    武汉      线下  308357.05
10   深圳      线下  733123.68
11   西安      线上   30088.01
12   西安      线下  180686.61
13   重庆      线上   26330.35
14   重庆      线下  237162.30

In [6]:
#透视表pivot_table()
#根据city和channel列创建透视表计算销售总额
print(df1.pivot_table(index='city', columns='channel', values='revenue', aggfunc='sum'))

channel         线上         线下
city
上海       114438.09  275383.64
北京             NaN  130458.62
南京             NaN  123150.93
广州       200893.30  117231.19
成都             NaN  208189.86
杭州             NaN  589518.49
武汉       281420.73  308357.05
深圳             NaN  733123.68
西安        30088.01  180686.61
重庆        26330.35  237162.30

In [7]:
house_df = pd.read_csv('LJdata.csv')
house_df.head()

,区域,地址,标题,户型,面积,价格,楼层,建造时间,朝向,更新时间,看房人数,备注,链接地址
0,燕莎租房,新源街,亮马桥 新源街 精装两居 交通便利 看房方便 随时入住,2室1厅,50,5800,中楼层(共6层),1981年建板楼,南,2017.07.21,26,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101803342.html
1,望京租房,澳洲康都,澳洲康都东向精致两居室...........,2室1厅,79,7800,中楼层(共28层),2005年建板塔结合,东,2017.07.23,33,距离14号线(东段)东湖渠站731米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101753126.html
2,广安门租房,远见名苑,远见名苑 东向两居室 独立小区环境 适合居家,2室1厅,86,8000,低楼层(共25层),2006年建塔楼,东,2017.07.20,34,距离7号线达官营站684米 随时看房 精装修 自供暖,https://bj.lianjia.com/zufang/101101756753.html
3,天通苑租房,天通苑北一区,北一区简装两居，采光好，视野美，出行方便,2室1厅,103,5300,低楼层(共13层),2004年建板楼,东南,2017.07.25,30,距离5号线天通苑站927米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101780034.html
4,团结湖租房,团结湖北口,团结湖北口近地铁高楼层朝南向精装修正规两居室,2室1厅,63,6400,高楼层(共16层),1982年建塔楼,南,2017.07.26,30,距离10号线团结湖站88米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101781083.html

In [8]:
#修改列名
house_df.rename(columns={'价格': 'price', '标题': 'title'}, inplace=True)
house_df.head()

,区域,地址,title,户型,面积,price,楼层,建造时间,朝向,更新时间,看房人数,备注,链接地址
0,燕莎租房,新源街,亮马桥 新源街 精装两居 交通便利 看房方便 随时入住,2室1厅,50,5800,中楼层(共6层),1981年建板楼,南,2017.07.21,26,随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101803342.html
1,望京租房,澳洲康都,澳洲康都东向精致两居室...........,2室1厅,79,7800,中楼层(共28层),2005年建板塔结合,东,2017.07.23,33,距离14号线(东段)东湖渠站731米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101753126.html
2,广安门租房,远见名苑,远见名苑 东向两居室 独立小区环境 适合居家,2室1厅,86,8000,低楼层(共25层),2006年建塔楼,东,2017.07.20,34,距离7号线达官营站684米 随时看房 精装修 自供暖,https://bj.lianjia.com/zufang/101101756753.html
3,天通苑租房,天通苑北一区,北一区简装两居，采光好，视野美，出行方便,2室1厅,103,5300,低楼层(共13层),2004年建板楼,东南,2017.07.25,30,距离5号线天通苑站927米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101780034.html
4,团结湖租房,团结湖北口,团结湖北口近地铁高楼层朝南向精装修正规两居室,2室1厅,63,6400,高楼层(共16层),1982年建塔楼,南,2017.07.26,30,距离10号线团结湖站88米 随时看房 精装修 集中供暖,https://bj.lianjia.com/zufang/101101781083.html

In [9]:
#查看数据维度
print(house_df.shape)

(2760, 13)

In [ ]:
#找到价格最高和最低的房子
print(house_df.nlargest(1, 'price'))#nlargest()函数返回DataFrame中指定列的前n个最大值所在
print('-----------------------------')
print(house_df.nsmallest(1, 'price'))#nsmallest()函数返回DataFrame中指定列的前n个最小值所在

         区域      地址               title    户型   面积   price        楼层  \
2658  和平里租房  雍和家园二期  雍和家园 底商出租 使用面积720米  6室3厅  720  210000  低楼层(共6层)

          建造时间 朝向        更新时间  看房人数                        备注  \
2658  2005年建板楼  南  2017.07.26    21   距离2号线雍和宫站293米 随时看房 集中供暖

                                                 链接地址
2658  https://bj.lianjia.com/zufang/101101672514.html
-----------------------------
        区域      地址                 title    户型  面积  price        楼层    建造时间  \
2527  良乡租房  伟业嘉园西里  半地下室 家电齐全 集中供暖 简单装修   1室1厅  46   1300  地下室(共5层)  2005年建

     朝向        更新时间  看房人数          备注  \
2527  南  2017.07.19    14   随时看房 集中供暖

                                                 链接地址
2527  https://bj.lianjia.com/zufang/101101538484.html